#!/bin/bash

echo "Usage: ./install.sh [OPTIONS]"
echo ""
echo "Options:"
echo "  -h, --help              Display this help message and exit"
echo "  -v, --version           Display the version number and exit"
echo "  -p, --path PATH         Set the installation path for dotfiles project (default: $INSTALL_PATH/dotfile)"
echo ""
echo "Description:"
echo "  The install.sh script is used to install the dotfiles project on your system. It supports the following options:"
echo ""
echo "  -h, --help              Display this help message and exit"
echo "                          This option displays the help message for the install.sh script."
echo ""
echo "  -v, --version           Display the version number and exit"
echo "                          This option displays the version number of the dotfiles project."
echo ""
echo "  -p, --path PATH         Set the installation path for dotfiles project (default: $INSTALL_PATH/dotfiles)"
echo "                          This option sets the installation path for the dotfiles project. If the specified path does not exist, it will be created."
echo ""
echo "  -f, --force             Forced Installation."
echo ""
echo "Examples:"
echo "  # Install the dotfiles project in the default location"
echo "  ./install.sh"
echo ""
echo "  # Install the dotfiles project in a custom location"
echo "  ./install.sh --path /opt/dotfiles"
echo ""
echo "  # Overwrite existing installation files"

