require('basic') -- 基础配置
require('keybindings') -- 快捷键配置
require('plugins') -- 插件配置
require('colorscheme') -- 主题配置
require('plugin-config.nvim-tree') -- 目录配置
require('plugin-config.bufferline') -- tab页配置
require('plugin-config.lualine') -- 状态栏配置
require('plugin-config.telescope') -- 搜索配置
require('plugin-config.dashboard') -- 启动页配置
require('plugin-config.project') -- 项目相关配置
require('plugin-config.nvim-treesitter') -- 语法高亮配置
require('lsp.setup') -- lsp配置
require('lsp.cmp') -- 自动补全配置
require('lsp.ui') -- lspUI配置
require('plugin-config.indent-blankline') -- 关联线配置
require('lsp.null-ls') -- 代码格式化配置
require('plugin-config.autopairs') -- 自动补全双括号之类
require('plugin-config.which-key') -- 快捷键映射配置
