name: Developer

on:
  push:
    tags:
      - '**'
    branches:
      - dev
jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: check zsh cli
        run: echo "hello world"


