name: Developer

on:
  push:
    tags:
      - '**'
    branches:
      - dev
jobs:
  linux-ubuntu:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, ubuntu-18.04, ubuntu-16.04]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: check zsh cli
        run: echo "hello world"


