name: Developer

on:
  push:
    tags:
      - '**'
    branches:
      - dev
jobs:
  linux-ubuntu:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20, ubuntu-18, ubuntu-16]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: check zsh cli
        run: pwd; ls -ahl; echo "hello world"
