name: Developer

on:
  push:
    tags:
      - '**'
    branches:
      - dev
      - master
jobs:
  Linux-ubuntu:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Install zsh
        run:  |
          cat ./src/tools/zsh_cli/install_zsh_cli.sh
          bash ./src/tools/zsh_cli/install_zsh_cli.sh
  Macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install zsh
        run:  |
          cat ./src/tools/zsh_cli/install_zsh_cli.sh
          bash ./src/tools/zsh_cli/install_zsh_cli.sh
  CentOS:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup CentOS
      uses: docker://centos:latest
      with:
        entrypoint: /bin/sh
        args: -c 'echo "Hello, CentOS!"'
