name: Developer

on:
  push:
    tags:
      - '**'
    branches:
      - dev
      - master
jobs:
  Linux-ubuntu:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Install zsh
        run:  |
          cat ./src/tools/zsh_cli/install_zsh_cli.sh
          bash ./src/tools/zsh_cli/install_zsh_cli.sh
  MacOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install zsh
        run:  |
          cat ./src/tools/zsh_cli/install_zsh_cli.sh
          bash ./src/tools/zsh_cli/install_zsh_cli.sh
  CentOS:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run CentOS container
        run: |
          docker run --rm -v "${PWD}:/app" -w /app centos:latest /bin/sh -c '
            cd /etc/yum.repos.d/
            sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
            sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
            cd -
            cat src/tools/zsh_cli/install_zsh_cli.sh 
            bash src/tools/zsh_cli/install_zsh_cli.sh 
          '
